extends Node

#region Teleport surface
signal s_teleport_surface
signal s_teleport_surface_done
#endregion

#region Break block UI
signal s_break_block_ui_begin
signal s_break_block_ui_end
signal s_break_block_ui_invalid_selection_begin
signal s_break_block_ui_invalid_selection_end
#endregion
